// @vitest-environment jsdom
import { mount, type VueWrapper } from '@vue/test-utils'
import { afterEach, describe, expect, it } from 'vitest'
import FactoryRecentBatches from './FactoryRecentBatches.vue'
import type { FactoryRecentBatch } from '@/types/factoryOverview'

const rows: FactoryRecentBatch[] = Array.from({ length: 7 }, (_, index) => ({ batch_no: `TL-${index}`, entry_kind: 'transfer', source_name: '库房', target_name: '轧制', external_destination: null, status: 'received', line_count: 1, quantity: 10, weight: 1, updated_at: '2026-09-27T12:00:00Z', received_at: '2026-09-27T10:00:00Z' }))
let wrapper: VueWrapper
afterEach(() => wrapper?.unmount())
const first = () => wrapper.get('tbody tr:first-child button').text()
const state = () => wrapper.get('tbody').attributes('style')

describe('recent batch playback', () => {
  it('shows the signed receipt time instead of the later update time, leaving unsigned rows blank', () => {
    wrapper = mount(FactoryRecentBatches, { props: { rows: [rows[0]!, { ...rows[1]!, status: 'pending', received_at: null }], motion: false } })
    expect(wrapper.get('h2').text()).toBe('今日转料动态')
    expect(wrapper.findAll('thead th').at(-1)!.text()).toBe('签收时间')
    const cells = wrapper.findAll('tbody tr td:last-child')
    expect(cells[0]!.get('time').attributes('datetime')).toBe('2026-09-27T10:00:00Z')
    expect(cells[0]!.text()).toBe('2026-09-27 18:00')
    expect(cells[1]!.text()).toBe('—')
    expect(cells[1]!.find('time').exists()).toBe(false)
    expect(wrapper.text()).not.toContain('2026-09-27 20:00')
  })
  it('cycles through every record and wraps without exposing the entering row to focus', async () => {
    wrapper = mount(FactoryRecentBatches, { props: { rows, motion: true } })
    expect(wrapper.text()).not.toMatch(/上一条|下一条/)
    for (let index = 0; index < rows.length; index++) {
      expect(first()).toBe(`TL-${index}`)
      expect(wrapper.findAll('tbody tr:not([aria-hidden])')).toHaveLength(3)
      expect(wrapper.get('tbody tr:last-child').attributes('inert')).toBeDefined()
      await wrapper.get('tbody').trigger('animationiteration')
    }
    expect(first()).toBe('TL-0')
    await wrapper.get('tbody tr:first-child button').trigger('click')
    expect(wrapper.emitted('open')).toEqual([[rows[0]]])
  })
  it('pauses for pointer, keyboard and explicit pause without losing the current record', async () => {
    wrapper = mount(FactoryRecentBatches, { props: { rows, motion: true } })
    await wrapper.trigger('mouseenter')
    expect(state()).toContain('paused')
    await wrapper.get('tbody').trigger('animationiteration')
    expect(first()).toBe('TL-0')
    await wrapper.trigger('mouseleave')
    expect(state()).toContain('running')
    await wrapper.get('.recent-table-scroll').trigger('focusin')
    expect(state()).toContain('paused')
    await wrapper.get('.recent-table-scroll').trigger('focusout', { relatedTarget: wrapper.get('tbody button').element })
    expect(state()).toContain('paused')
    await wrapper.get('.recent-table-scroll').trigger('focusout', { relatedTarget: null })
    expect(state()).toContain('running')
    await wrapper.get('[aria-label="暂停今日转料"]').trigger('click')
    expect(state()).toContain('paused')
    await wrapper.get('tbody').trigger('animationiteration')
    expect(first()).toBe('TL-0')
    expect(state()).toContain('paused')
    await wrapper.get('[aria-label="播放今日转料"]').trigger('click')
    expect(state()).toContain('running')
    await wrapper.get('tbody').trigger('animationiteration')
    expect(first()).toBe('TL-1')
  })
  it('stops automatic motion while hidden or reduced and resumes at the same record', async () => {
    wrapper = mount(FactoryRecentBatches, { props: { rows, motion: true } })
    await wrapper.get('tbody').trigger('animationiteration')
    await wrapper.setProps({ motion: false })
    expect(wrapper.find('.recent-rolling').exists()).toBe(false)
    await wrapper.get('tbody').trigger('animationiteration')
    expect(first()).toBe('TL-1')
    await wrapper.setProps({ motion: true })
    expect(state()).toContain('running')
    expect(first()).toBe('TL-1')
  })
  it('shows fresh records and handles short or empty reports without animation', async () => {
    wrapper = mount(FactoryRecentBatches, { props: { rows, motion: true } })
    for (let index = 0; index < 6; index++) await wrapper.get('tbody').trigger('animationiteration')
    expect(first()).toBe('TL-6')
    await wrapper.setProps({ rows: [{ ...rows[0]!, batch_no: 'TL-NEW' }, ...rows] })
    expect(first()).toBe('TL-NEW')
    await wrapper.setProps({ rows: rows.slice(0, 2) })
    expect(wrapper.findAll('tbody tr')).toHaveLength(2)
    expect(wrapper.find('.recent-pagination').exists()).toBe(false)
    expect(wrapper.find('.recent-rolling').exists()).toBe(false)
    await wrapper.setProps({ rows: [] })
    expect(wrapper.text()).toContain('今日暂无转料记录')
    expect(wrapper.find('table').exists()).toBe(false)
  })
})
